# Notions d'algèbre linéaire


## Introduction

Ce document est un traduction "libre" et approximative du cours de Zico Kolter : [Linear Algebra Review and Reference](https://see.stanford.edu/materials/aimlcs229/cs229-linalg.pdf). Les lecteurs sont fortement encouragés à se référer au document d'origine!


## Concepts de base et notation

L'algèbre linéaire fournit les outils permettant de représenter et manipuler simplement des ensembles d'équations linaires.

\begin{align}
     4 x_1 - 5 x_2 & = -13 \\
    -2 x_1 + 3 x_2 & =  9  
\end{align}

Il est possible à partir de ces deux équiations à deux variables de trouver une unique solution pour $x_1$ et $x_2$ (à moins que les équations soient en quelque sorte dégénérées, par exemple si la seconde équation est un multiple de la première). Dans notre exemple il n'y a une solution unique. En notation matricielle, le système précédent peut être écrit de manière plus compacte :

\begin{equation*}
Ax=b \\
\text{ avec } A = \begin{bmatrix}
    4  & -5 \\
    -2 & 3
\end{bmatrix} 
\text{ , }
b = \begin{bmatrix}
-13 \\
9
\end{bmatrix} 
\end{equation*}

### Exemple de définition numpy

L'exemple précédent peut s'écrire de la manière suivante avec numpy :

In [13]:
import numpy as np
A = np.matrix([[4,-5], [-2, 3]])
b = np.matrix([-13,9]).transpose()
print("A = \n",A)
print("b = \n",b)

A = 
 [[ 4 -5]
 [-2  3]]
b = 
 [[-13]
 [  9]]




## Notations de base

Nous utilisons les notations suivantes:

- $A \in \mathbb{R}^{m \times n}$ définit une matrice ayant $m$ lignes et $n$ colonnes dans laquelle les élements sont des nombres réels.

- $x \in \mathbb{R}^n$ définit un vecteur à $n$ éléments. Généralement un vecteur $x$ est un **vecteur en colonne**, c'est à dire une matrice ayant une ligne et $n$ colonnes (soit une matrice $\mathbb{R}^{1 \times n}$). Si l'on veut décrire un **vecteur ligne** ayant 1 ligne et $n$ colonnes, on écrit $x^T$ ($x^T$ veut dire la transposée de $x$, que nous allons décrire bientôt). 

- Le $i^{eme}$ élément d'un vecteur $x$ se note $x_i$ :

\begin{equation*}
x = \begin{bmatrix}
x_1 \\
x_2 \\
\vdots \\
x_n
\end{bmatrix}
\end{equation*}

- La notation $a_ij$ (ou $A_{ij}$, $A_{i , j}$, etc) définit l'élément de $A$ présent à la $i^{eme}$ ligne et à la $j^{ieme}$ colonne:

\begin{equation*}
A = \begin{bmatrix}
a_{11} & a_{12} & \dots & a_{1n} \\
a_{21} & a_{22} & \dots & a_{2n} \\
\vdots & \vdots & \ddots & \vdots \\
a_{m1} & a_{m2} & \dots & a_{mn}
\end{bmatrix}
\end{equation*}

- La $j^{eme}$ colonne de A se note $a_j$ ou $A_{:,j}$ :

\begin{equation*}
A = \begin{bmatrix}
\rvert & \rvert	&       & \rvert \\
a_1 & a_2 & \dots & a_n \\
\rvert & \rvert	&       & \rvert 
\end{bmatrix}
\end{equation*}

- La $i^{eme}$ ligne de A se note $a_i^T$ ou $A_{i,:}$ :

\begin{equation*}
A = \begin{bmatrix}
- & a_1^T & - \\
- & a_2^T & - \\
  & \vdots & \\
- & a_m^T & - 
\end{bmatrix}
\end{equation*}


### Manipulation avec numpy 

> Dans numpy la première ligne et la premiere colonne commencent à 0 et non à 1 comme dans les conventions mathématiques classiques.

In [23]:
a22 = A[1,1]
print("La valeur de l'element a22 est :\n",a22)

a2 = A[:,1]
print("Le vecteur de la deuxieme colonne a2 est :\n",a2)

aT2 = A[1,:]
print("Le vecteur de la deuxieme ligne aT2 est :\n",aT2)

La valeur de l'element a22 est :
 3
Le vecteur de la deuxieme colonne a2 est :
 [[-5]
 [ 3]]
Le vecteur de la deuxieme ligne aT2 est :
 [[-2  3]]
